version: "3"

tasks:
  build:
    sources:
      - ./src/**/*
      - ./taskfile.yaml
    generates:
      - ./dist/assets/**
      - ./dist/index.html
    cmds:
      - |
        npm ci
        npm run build
  deploy:
    cmds:
      - task: build
      - |
        aws s3 cp --recursive ./dist/ s3://"{{.DRAWINGS_BUCKET_NAME}}"/client/

